version: '3.9'
services:
  db:
    image: 'postgres:14.5'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend

  db-migration:
    image: 'liquibase/liquibase:4.16'
    profiles:
      - tools
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./database/liquibase.properties:/liquibase/liquibase.properties
      - ./database/changelog:/liquibase/changelog/
      - ./database/changelog/_root.sql:/liquibase/changelog.sql
    command: liquibase --changelog-file=_root.sql update
    # command: liquibase rollback-count 1 # rollback one changeset

  server:
    build: .
    env_file:
      - .env
    ports:
      - ${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: npm run dev

  server-dev:
    profiles:
      - dev
    build:
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    ports:
      - ${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  db-data:
    driver: local

networks:
  backend:
    driver: bridge
