version: '3.9'
services:
  db:
    image: 'postgres:14.5'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend

  server:
    build: .
    env_file:
      - .env
    ports:
      - ${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}
    networks:
      - backend
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  db-data:
    driver: local

networks:
  backend:
    driver: bridge
